/* BOARDS.H */

#ifndef GT_BOARDS_H
#define GT_BOARDS_H


/* Gtalk */
/* Copyright (C) 1993, by David W Jeske, and Daniel L Marks */
/* Copying or distributing this source code without written  */
/* permission of David W Jeske and Daniel L Marks is strictly forbidden */

#define BOARD_TYPE_CONSOLE 0
#define BOARD_TYPE_x450_COM 1
#define BOARD_TYPE_DUMB_DIGI 2
#define BOARD_TYPE_SMART_DIGI 3
#define BOARD_TYPE_STARGATE_ACL 4
#define BOARD_TYPE_LIGHTSPEED 5
#define BOARD_TYPE_OS2_COM 6


#endif
