/* gtalk.h */
/* includes all gtalk standard includes */

#ifndef GT_GTALK_H
#define GT_GTALK_H


/* Gtalk */
/* Copyright (C) 1993, by David W Jeske, and Daniel L Marks */
/* Copying or distributing this source code without written  */
/* permission of David W Jeske and Daniel L Marks is strictly forbidden */


#include "define.h"
#include "function.h"

#include "task.h"
#include "init.h"
#include "alloc.h"
#include "channel.h"
#include "input.h"
#include "output.h"
#include "abuf.h"
#include "syslog.h"
#include "gt.h"
#include "user.h"
#include "command.h"
#include "link.h"
#include "glink.h"
#include "structs.h"
#include "string.h"

#include "privs.h"
#include "toggles.h"

#include "editor.h"
#include "mail.h"
#include "rotator.h"
#include "gfiles.h"

#include "schedule.h"
#include "sysop.h"
#include "bbs.h"
#include "diags.h"
#include "protocol.h"
#include "filesec.h"

#define strncmp g_strncmp


#endif /* GT_GTALK_H */
