/* INCLUDE.H */

#ifndef GT_INCLUDE_H
#define GT_INCLUDE_H


/* Gtalk */
/* Copyright (C) 1993, by David W Jeske, and Daniel L Marks */
/* Copying or distributing this source code without written  */
/* permission of David W Jeske and Daniel L Marks is strictly forbidden */


#include <stdio.h>
#include <dos.h>
#include <alloc.h>
#include <conio.h>
#include <stdlib.h>
#include <ctype.h> /* toupper */
#include <string.h>
#include <time.h>
#include <mem.h>
#include <dir.h>
#include <stdarg.h>


#endif /* GT_INCLUDE_H */
