/* string.h */

#ifndef GT_STRING_H
#define GT_STRING_H

/* Gtalk */
/* Copyright (C) 1993, by David W Jeske, and Daniel L Marks */
/* Copying or distributing this source code without written  */
/* permission of David W Jeske and Daniel L Marks is strictly forbidden */


void deencrypt(void);

extern char info_string[];
extern char by_line[];
extern char ginsutalk_line[];
extern char copyright_mesg[];
extern char po_box_line[];
extern char glenview_il[];
extern char system_startup[];
extern char nuke_greenhouse[];
extern char information_question[];
extern char company_name[];


#endif /* GT_STRING_H */

